export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_USE_DEVICE_MODE = 'CHANGE_USE_DEVICE_MODE';

export const ADD_PLAYER = 'ADD_PLAYER';

export const CREATE_GAME = 'CREATE_GAME';
